config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :suppliers, only: %i[index create edit update] do
    resources :documents, only: %i[new index create]
    resources :analyse_supp_docs, only: %i[create index]
  end
  resources :batches, only: %i[index create edit update] do
    resources :documents, only: %i[new index create]
    resources :batch_docs, only: :index
  end
  resources :products, only: %i[index create edit update] do
    resources :documents, only: %i[new index create]
  end
  resources :batch_docs, only: %i[edit update]

  get 'buy', to: 'pages#buy', as: 'buy'
  get 'quality', to: 'pages#quality', as: 'quality'
  get 'sale', to: 'pages#sale', as: 'sale'
  get 'transport', to: 'pages#transport', as: 'transport'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
  </div>
  <div class="footer-copyright">
    V-1.0 2022 Ciacam
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-1 border-bottom border-warning border-2">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "ciacam.webp", height: 50 %>
  <% end %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Planning", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown dropdown-toggle nav-link" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
          <%= current_user.email %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Profil", "#", class: "dropdown-item" %>
            <%= link_to "Deconnection", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Connection", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class='sidebar-log text-center border border-top-0 border-start-0 border-bottom-0 position-relative' style="width:16vh; " >
  <div class="sidebar-log side-tabs position-absolute">
    <div class="side-link text-start py-1 ms-2 <%= "active" if params["action"] == "buy" %>" >
      <%= link_to buy_path do %>
        <i class="fa-solid fa-basket-shopping" style="font-size:18px"></i><span class="appear-link ms-2"> ACHAT </span>
      <% end %>
    </div>
    <div class="side-link text-start py-1 ms-2 <%= "active" if params["action"] == "quality" %>">
      <%= link_to quality_path do %>
        <i class="fa-solid fa-vial-circle-check" style=" font-size:18px"></i><span class="appear-link ms-2"> QUALITE </span>
      <% end %>
    </div>
    <div class="side-link text-start py-1 ms-2 <%= "active" if params["action"] == "sale" %>" >
      <%= link_to sale_path do %>
        <i class="fa-solid fa-cash-register" style="font-size:18px"></i><span class="appear-link ms-2"> VENTE </span>
      <% end %>
    </div>
    <div class="side-link text-start py-1 ms-2 <%= "active" if params["action"] == "transport" %>">
      <%= link_to transport_path do %>
        <i class="fa-solid fa-truck" style="font-size:18px"></i><span class="appear-link ms-2"> FRET </span>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_tabs.html.erb
<div class="tabs border-0">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
  <% case params['action'] %>
  <% when 'buy' %>
    <li class="nav-item" >
      <%= link_to batches_path, class: 'nav-link', data: {bs_toggle: 'tab',
                                                  bs_target: '#batch',
                                                  content_target: 'batch',
                                                  action: 'click->content#batch'
                                                }   do %>
        <%= 'Lots' %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to suppliers_path, class: 'nav-link', data: {bs_toggle: 'tab',
                                                            bs_target: '#supllier',
                                                            content_target: 'supplier',
                                                            action: 'click->content#supplier'} do %>
        <%= 'Fournisseurs' %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to products_path, class: 'nav-link', data: {bs_toggle: 'tab',
                                                 bs_target: '#product',
                                                 content_target: 'product',
                                                 action: 'click->content#product'} do %>
        <%= 'Produits' %>
      <% end %>
    </li>
  <% when 'quality' %>
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="#" id="home-tab" data-bs-toggle="tab" data-bs-target="#lot" type="button" role="tab" aria-controls="lot" aria-selected="true">
        <%= 'Analyse' %>
      </a>
    </li>
    <li class="nav-item" >
      <a class="nav-link" aria-current="page" href="#" id="home-tab" data-bs-toggle="tab" data-bs-target="#lot" type="button" role="tab" aria-controls="lot" aria-selected="false">
        <%= 'Certificats à renouveller' %>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" aria-current="page" href="#" id="home-tab" data-bs-toggle="tab" data-bs-target="#lot" type="button" role="tab" aria-controls="lot" aria-selected="false">
        <%= 'Cahier des charges' %>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" aria-current="page" href="#" id="home-tab" data-bs-toggle="tab" data-bs-target="#lot" type="button" role="tab" aria-controls="lot" aria-selected="false">
        <%= 'Document qualité' %>
      </a>
    </li>
  <% when 'sale' %>
    <li class="nav-item" >
      <a class="nav-link active" aria-current="page" href="#" id="home-tab" data-bs-toggle="tab" data-bs-target="#batch" type="button" role="tab" aria-controls="lot" aria-selected="true">
        <%= 'Commandes clients' %>
      </a>
    </li>
    <li class="nav-item" >
      <a class="nav-link" aria-current="page" href="#" id="home-tab" data-bs-toggle="tab" data-bs-target="#supplier" type="button" role="tab" aria-controls="lot" aria-selected="false">
        <%= 'Refus' %>
      </a>
    </li>
      <% when 'transport' %>
    <li class="nav-item" >
      <a class="nav-link active" aria-current="page" href="#" id="home-tab" data-bs-toggle="tab" data-bs-target="#product" type="button" role="tab" aria-controls="lot" aria-selected="true">
        <%= 'Transports en cours' %>
      </a>
    </li>
    <li class="nav-item" >
      <a class="nav-link" aria-current="page" href="#" id="home-tab" data-bs-toggle="tab" data-bs-target="#lot" type="button" role="tab" aria-controls="lot" aria-selected="false">
        <%= 'Transports chargés' %>
      </a>
    </li>
    <% end %>
    <li class="flex-grow-1 no-use-tabs"></li>
  </ul>
</div>