config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :suppliers, only: %i[index create edit update] do
    resources :documents, only: %i[new index create]
    resources :analyse_supp_docs, only: %i[create index]
  end
  resources :batches, only: %i[index create edit update] do
    resources :documents, only: %i[new index create]
    resources :batch_docs, only: :index
  end
  resources :products, only: %i[index create edit update] do
    resources :documents, only: %i[new index create]
  end
  resources :batch_docs, only: %i[edit update]

  get 'buy', to: 'pages#buy', as: 'buy'
  get 'quality', to: 'pages#quality', as: 'quality'
  get 'sale', to: 'pages#sale', as: 'sale'
  get 'transport', to: 'pages#transport', as: 'transport'
end

app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :supplier
  belongs_to :product
  has_many :documents, dependent: :destroy
  has_many :batch_docs, dependent: :destroy
  has_rich_text :rich_info

  validates :number, presence: true

  after_create do
    create_batch_doc if transportation == 2
  end

  STATUS = [[0, "Copie reçu"],
            [1, "Doc en banque"],
            [2, "Payé"],
            [3, "Docs envoyé par la banque"],
            [4, "Docs originaux reçu"],
            [5, "Bl envoyé ou déposé à la compagnie"]]

  private

  def create_batch_doc
    BatchDoc::BATCH.each do |title|
      BatchDoc.create(title: title, status: 2, batch: self)
    end
  end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  def index
    @batchs = policy_scope(Batch).sort_by { |e| -e.number }

    respond_to do |format|
      format.html { render 'pages/buy' }
      format.json # Follow the classic Rails flow and look for a create.json view
    end
  end

  def create
    @batchs = policy_scope(Batch)
    @batch = Batch.create(batch_params)
    authorize @batch
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.json # Follow the classic Rails flow and look for a create.json view
    end
  end

  def edit
    @batch = Batch.find(params[:id])
    authorize @batch
    respond_to do |format|
      format.html { render 'pages/buy' }
      format.json # Follow the classic Rails flow and look for a edit.json view
    end
  end

  def update
    @batchs = policy_scope(Batch)
    @batch = Batch.find(params[:id])
    @batch.update(batch_params)
    authorize @batch
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.json # Follow the classic Rails flow and look for a update.json view
    end
  end

  private

  def batch_params
    params.require(:batch).permit(:number, :quantity, :transportation, :product_id, :supplier_id, :discharge_place,
                                  :bank, :status, :origin, :info, :rich_info)
  end
end

app/views/batches/_card_batch.html.erb
<% if batchs.count > 0 %>

    <% batchs.each do |batch| %>
      <div data-controller='info' >
        <div data-controller="document" >
          <div data-controller="index-batch-doc">
            <div data-document-target="card">
              <div class="card-batch mt-5">
                <% if batch.product.photo.attached? %>
                  <%= cl_image_tag batch.product.photo.key, height: 300, width: 400, crop: :fill %>
                <% else %>
                  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
                <% end %>
                <h2 data-info-target='number' class='mt-1 ms-2'>Lot : <%= batch.number %></h2>
                <div data-info-target='info' class="card-batch-infos">
                  <div>
                    <p><strong><%= batch.supplier.name %></strong></p>
                    <p><%= batch.product.name %></p>
                    <p><%= batch.origin %></p>
                    <p><%= batch.quantity %> T</p>
                    <% if batch.transportation == 1 %>
                      <p> Route </p>
                      <p> Usine de déchargement <%= batch.discharge_place %></p>
                    <% elsif batch.transportation == 2 %>
                      <p> Maritime </p>
                      <p> Port de déchargement <%= batch.discharge_place %></p>
                    <% end %>
                  </div>
                  <div>
                    <% if batch.transportation == 2 %>
                      <p><%= batch.bank && batch.bank != "" ? "Banque : #{batch.bank}" : "Aucune banque associé"  %></p>
                      <% if batch.status %>
                        <% case batch.status %>
                        <% when 0 %>
                          <p> Copie reçu</p>
                        <% when 1 %>
                          <p> Doc en banque</p>
                        <% when 2 %>
                          <p> Payé</p>
                        <% when 3 %>
                          <p> Docs envoyé par la banque </p>
                        <% when 4 %>
                          <p> Docs originaux reçu</p>
                        <% when 5%>
                          <p> Bl envoyé ou déposé à la compagnie</p>
                        <% else %><p> En attente </p>
                        <% end %>
                      <% end %>
                        <p><%= batch.rich_info %></p>
                    <% end %>
                  </div>
                </div>
                <div class="card-batch-edit" >
                  <%= link_to edit_batch_path(batch), class: 'me-4', data: {
                                                      info_target: "model",

                                                      action:"click->info#info"
                                                    },
                                                    style: 'text-decoration: none; color: black' do %>
                    <i class="fa-solid fa-pen-to-square"></i>
                  <% end %>
                  <%= link_to batch_documents_path(batch), class: 'me-4', data: {
                                              document_target: 'doc',
                                              action: 'click->document#info'
                                              },
                                              style: 'text-decoration: none; color: black' do  %>
                    <i class="fa-regular fa-file-lines"></i>
                  <% end %>
                  <%= link_to new_batch_document_path(batch), class: 'me-4', data: {
                                          document_target: 'new',
                                          action: 'click->document#new'
                                          }, style: 'text-decoration: none; color: black' do   %>
                    <i class="fa-solid fa-folder-plus"></i>
                  <% end %>
                  <% if batch.transportation == 2 %>
                    <%= link_to batch_batch_docs_path(batch), class: 'me-4', data: {
                                              index_batch_doc_target: 'new',
                                              action: 'click->index-batch-doc#new'
                                              }, style: 'text-decoration: none; color: black' do   %>
                      <i class="fa-solid fa-list"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div data-info-target='insert' data-document-target='insert' data-index-batch-doc-target='insert' style='background:white'></div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

<% else %>
  <h1>Vous n'avez pas de lots</h1>
<% end %>

app/views/batches/_error.html.erb
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= "Une erreur c'est produite, le produit n'a pas été enregistré" %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>

app/views/batches/_form.html.erb
<div class="p-3 d-flex justify-content-between">
  <%= simple_form_for(batch,
                      data: {
                        info_target: "form",
                        action: "submit->info#send"
                        }) do |f| %>
    <%= f.input :number, label: false, input_html: {placeholder: 'Numero de lot', data: { create_target: 'input'}}  %>
    <%= f.input :quantity, label: false, input_html: {placeholder: 'Quantité en tonne', data: { create_target: 'input'}}  %>
    <%= f.input :supplier_id, collection: Supplier.all, label: false, input_html: {placeholder: 'Fournisseur', data: { create_target: 'input'}} %>
    <%= f.input :product_id, collection: Product.all, label: false, input_html: {placeholder: 'Produit', data: { create_target: 'input'}} %>
    <%= f.input :origin, label: false, input_html: {placeholder: 'Origine', data: { create_target: 'input'}} %>
    <div class='mb-2'>
      <%= f.collection_radio_buttons :transportation, [[1, 'Route'], [2, 'Maritime']], :first, :last,  item_label_class:'px-2 ' %>
    </div>
    <%= f.input :discharge_place, label: false, input_html: {placeholder: 'Lieu de déchargement'} %>
    <% if batch.transportation == 2 %>
      <div id="trix-toolbar">
        <%= f.rich_text_area :rich_info %>
      </div>
      <%= f.input :bank, label: false, input_html: {placeholder: 'Banque'} %>
      <%= f.collection_radio_buttons :status, Batch::STATUS, :first, :last, item_wrapper_tag: :div, item_label_class:'mx-1' %>
    <% end %>
    <%= f.button :submit, 'Valider', class: 'btn btn-outline-primary', data: {
                                                              disable_with: false,
                                                            } %>

  <% end %>
  <div data-action="click->info#close">
    <i class="fa-solid fa-xmark"></i>
  </div>
</div>

app/views/batches/_index.html.erb
<div class="m-4"data-controller="create" data-create-target="index" >
  <div class="container">
    <div class="row">

<!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#productModal" style="width:350px;">
        <i class="fa-sharp fa-solid fa-plus"></i> Ajouter un nouveau lot
      </button>

<!-- Modal -->
      <div class="modal fade" id="productModal" tabindex="-1" aria-labelledby="productModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">Nouveau lot</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="col-8 m-3">


              <%= simple_form_for(batch,
                      data: {
                        info_target: "form",
                        action: "submit->info#send"
                        }) do |f| %>
                <%= f.input :number, label: false, input_html: {placeholder: 'Numero de lot', data: { create_target: 'input'}}  %>
                <%= f.input :quantity, label: false, input_html: {placeholder: 'Quantité en tonne', data: { create_target: 'input'}}  %>
                <%= f.input :supplier_id, collection: Supplier.all.sort_by { |e| e.name }, label: false, input_html: {placeholder: 'Fournisseur', data: { create_target: 'input'}} %>
                <%= f.input :product_id, collection: Product.all.sort_by { |e| e.name }, label: false, input_html: {placeholder: 'Produit', data: { create_target: 'input'}} %>
                <%= f.input :origin, label: false, input_html: {placeholder: 'Origine', data: { create_target: 'input'}} %>
                <div class='mb-2'>
                  <%= f.collection_radio_buttons :transportation, [[1, 'Route'], [2, 'Maritime']], :first, :last,  item_label_class:'px-2 ' %>
                </div>
                <%= f.input :discharge_place, label: false, input_html: {placeholder: 'Lieu de déchargement'} %>
                <% if batch.transportation == 2 %>
                  <%= f.input :bank, label: false, input_html: {placeholder: 'Banque'} %>
                <% end %>
                <%= f.button :submit, 'Mettre à jour', class: 'btn btn-outline-primary', data: {
                                                                          disable_with: false,
                                                                        } %>

              <% end %>

            </div>
          </div>
        </div>
      </div>
    <div data-create-target='insert'></div>
    <div data-content-target="insertCard" class='cards'></div>
  </div>
</div>

app/views/batches/_info_batch.html.erb
      <div class="card-product-infos">
        <p><%= batch.supplier.name %></p>
        <p><%= batch.product.name %></p>
        <p><%= batch.quantity %></p>
        <% if batch.transportation == 1 %>
          <p> Route </p>
        <% elsif batch.transportation == 2 %>
          <p> Maritime </p>
        <% end %>
      </div>

app/views/batches/_info_batch_number.html.erb
<h2><%= batch.number %></h2>

app/views/batches/_new_batch.html.erb
<div class="alert alert-primary alert-dismissible fade show m-1" role="alert">
  <%= "Lots bien enregistré" %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>


 <div class="card-product mt-5">
    <% if batch.product.photo.attached? %>
      <%= cl_image_tag batch.product.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
    <% end %>
    <h2><%= batch.number %></h2>
  <div class="card-product-infos">
    <p><%= batch.supplier.name %></p>
    <p><%= batch.product.name %></p>
    <p><%= batch.quantity %></p>
    <% if batch.transportation == 1 %>
      <p> Route </p>
    <% elsif batch.transportation == 2 %>
      <p> Maritime </p>
    <% end %>
  </div>
</div>

app/views/batches/_update_batch.html.erb
<div class="alert alert-primary alert-dismissible fade show m-1" role="alert">
  <%= "Lot bien enregistré" %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>