config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :suppliers, only: %i[index create edit update] do
    resources :documents, only: %i[new index create]
    resources :analyse_supp_docs, only: %i[create index]
  end
  resources :batches, only: %i[index create edit update] do
    resources :documents, only: %i[new index create]
    resources :batch_docs, only: :index
  end
  resources :products, only: %i[index create edit update] do
    resources :documents, only: %i[new index create]
  end
  resources :batch_docs, only: %i[edit update]

  get 'buy', to: 'pages#buy', as: 'buy'
  get 'quality', to: 'pages#quality', as: 'quality'
  get 'sale', to: 'pages#sale', as: 'sale'
  get 'transport', to: 'pages#transport', as: 'transport'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :batches, dependent: :destroy
  has_many :analyse_supp_docs, dependent: :destroy
  has_many :documents, dependent: :destroy
  validates :name, presence: true
  has_one_attached :photo
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = policy_scope(Product).sort_by { |e| e.name}
    respond_to do |format|
      format.html { render 'pages/buy' }
      format.json # Follow the classic Rails flow and look for a index.json view
    end
  end

  def create
    @products = policy_scope(Product)
    @product = Product.create(product_params)
    authorize @product
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.json # Follow the classic Rails flow and look for a create.json view
    end
  end

  def edit
    @product = Product.find(params[:id])
    authorize @product
    respond_to do |format|
      format.html { render 'pages/buy' }
      format.json # Follow the classic Rails flow and look for a edit.json view
    end
  end

  def update
    @products = policy_scope(Product)
    @product = Product.find(params[:id])
    @product.update(product_params)
    authorize @product
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.json # Follow the classic Rails flow and look for a update.json view
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :photo)
  end
end

app/views/products/_card_product.html.erb
<% if products.count > 0 %>
  <% products.each do |product| %>
    <div data-controller="info" >
      <div data-controller="document" >
        <div data-document-target="card">
          <div class="card-product mt-5">
            <% if product.photo.attached? %>
              <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill %>
            <% else %>
              <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
            <% end %>
            <div data-info-target='info' class="card-product-infos flex-grow-1">
              <h2><%= product.name %></h2>
            </div>
            <div class="card-product-edit" >
              <%= link_to edit_product_path(product), class: 'me-4', data: {
                                                    info_target: "model",
                                                    action:"click->info#info"
                                                  },
                                                  style: 'text-decoration: none; color: black' do %>
                <i class="fa-solid fa-pen-to-square"></i>
              <% end %>
              <%= link_to product_documents_path(product), class: 'me-4', data: {
                                              document_target: 'doc',
                                              action: 'click->document#info'
                                              },
                                              style: 'text-decoration: none; color: black' do  %>
                <i class="fa-regular fa-file-lines"></i>
              <% end %>
              <%= link_to new_product_document_path(product), class: 'me-4', data: {
                                                    document_target: 'new',
                                                    action: 'click->document#new'
                                                    }, style: 'text-decoration: none; color: black' do   %>
                        <i class="fa-solid fa-folder-plus"></i>
              <% end %>
            </div>
          </div>
          <div data-info-target='insert' data-document-target='insert' style='background:white'></div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <h1>Vous n'avez pas de lots</h1>
<% end %>

app/views/products/_error.html.erb
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= "Une erreur c'est produite, le produit n'a pas été enregistré" %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>

app/views/products/_form.html.erb
<div class="p-3 d-flex justify-content-between">
  <%= simple_form_for(product,
                      data: {
                        info_target: "form",
                      action: "submit->info#send"
                      }, html: { enctype:"multipart/form-data"}) do |f| %>
    <%= f.input :name, label: false, input_html: {placeholder: 'nom du produit', style: 'width: 300px'}  %>
    <%= f.input :photo, as: :file, label: 'Selectionner une photo', input_html: {class:'d-none', style: 'width: 300px'}, wrapper_html: {class:'d-flex justify-content-around align-items-center'},
                                                                    label_html: {class: 'btn btn-primary'}%>
    <%= f.button :submit, 'Mettre à jour', class: 'btn btn-outline-primary', data: {
                                                                              disable_with: false
                                                                              } %>

  <% end %>
  <div data-action="click->info#close">
    <i class="fa-solid fa-xmark"></i>
  </div>
</div>

app/views/products/_index.html.erb
<div class="m-4"data-controller="create" data-create-target="index" >
  <div class="container">
    <div class="row">

<!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#productModal" style="width:350px;">
        <i class="fa-sharp fa-solid fa-plus"></i> Ajouter un nouveau produit
      </button>

<!-- Modal -->
      <div class="modal fade" id="productModal" tabindex="-1" aria-labelledby="productModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">Nouveau produit</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="col-8 m-3">
              <%= simple_form_for(product,
                                    data: {
                                            create_target: "form",
                                            action: "submit->create#send"
                                            }) do |f| %>
                <%= f.input :name, label: false, input_html: {placeholder: 'nom du produit', data: { create_target: 'input'}}  %>
                <%= f.input :photo, as: :file %>
                <%= f.button :submit, 'Créer', class: 'btn btn-outline-primary', data: {
                                                                              disable_with: false,
                                                                              bs_dismiss: 'modal'
                                                                              } %>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div data-create-target='insert'></div>
    <div data-content-target="insertCard"></div>
</div>

app/views/products/_info_product.html.erb
<h2><%= product.name %></h2>

app/views/products/_new_product.html.erb
<div class="alert alert-primary alert-dismissible fade show m-1" role="alert">
  <%= "Produit bien enregistré" %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>

<div data-controller="info" style='background:white'>
      <div class="card-product mt-5">
        <% if product.photo.attached? %>
          <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <% end %>
        <div class="card-product-infos flex-grow-1">
          <h2><%= product.name %></h2>
          <p>Product description with <strong>relevant info</strong> only.</p>
        </div>
        <div class="card-product-edit">
          <%= link_to edit_product_path(product), class: 'me-4', data: {
                                                info_target: "model",
                                                action:"click->info#info"
                                              },
                                              style: 'text-decoration: none; color: black' do %>
            <i class="fa-solid fa-circle-info"></i>
          <% end %>
        </div>
      </div>
      <div data-info-target='insert'  class="mt-3"></div>
    </div>
</div>

app/views/products/_update_product.html.erb
<div class="alert alert-primary alert-dismissible fade show m-1" role="alert">
  <%= "Produit bien enregistré" %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>