config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :suppliers, only: %i[index create edit update] do
    resources :documents, only: %i[new index create]
    resources :analyse_supp_docs, only: %i[create index]
  end
  resources :batches, only: %i[index create edit update] do
    resources :documents, only: %i[new index create]
    resources :batch_docs, only: :index
  end
  resources :products, only: %i[index create edit update] do
    resources :documents, only: %i[new index create]
  end
  resources :batch_docs, only: %i[edit update]

  get 'buy', to: 'pages#buy', as: 'buy'
  get 'quality', to: 'pages#quality', as: 'quality'
  get 'sale', to: 'pages#sale', as: 'sale'
  get 'transport', to: 'pages#transport', as: 'transport'
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :batches, dependent: :destroy
  has_many :Loading_place, dependent: :destroy
  has_many :documents, dependent: :destroy
  has_many :analyse_supp_docs, dependent: :destroy
  validates :name, presence: true
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    @suppliers = policy_scope(Supplier).sort_by { |e| e.name }
    # @suppliers = @suppliers.sort_by { |e| e.name}
    respond_to do |format|
      format.html { render 'pages/buy' }
      format.json # Follow the classic Rails flow and look for a index.json view
    end
  end

  def create
    @supplies = policy_scope(Supplier)
    @supplier = Supplier.create(supplier_params)
    authorize @supplier
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.json # Follow the classic Rails flow and look for a create.json view
    end
  end

  def edit
    @supplier = Supplier.find(params[:id])
    authorize @supplier
    respond_to do |format|
      format.html { render 'pages/buy' }
      format.json # Follow the classic Rails flow and look for a edit.json view
    end
  end

  def update
    @suppliers = policy_scope(Supplier)
    @supplier = Supplier.find(params[:id])
    @supplier.update(supplier_params)
    authorize @supplier
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.json # Follow the classic Rails flow and look for a update.json view
    end
  end

  private

  def supplier_params
    params.require(:supplier).permit(:name, :contact, :bio)
  end
end

app/views/suppliers/_card_supplier.html.erb
<% if suppliers.count > 0 %>
  <% suppliers.each do |supplier| %>
    <div data-controller="info">
      <div data-controller="document" >
        <div data-document-target="card">
          <div class="card-product mt-5" >
            <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
            <div data-info-target='info' class="card-product-infos flex-grow-1">
              <h2><%= supplier.name %></h2>
            </div>
            <div class="card-product-edit" >
                <%= link_to edit_supplier_path(supplier), class: 'me-4', data: {
                                                      info_target: "model",
                                                      action:"click->info#info"
                                                    },
                                                    style: 'text-decoration: none; color: black' do %>
                  <i class="fa-solid fa-pen-to-square"></i>
                <% end %>
                <% if supplier.documents.count.positive? || supplier.analyse_supp_docs.count.positive? %>
                  <%= link_to supplier_documents_path(supplier), class: 'me-4', data: {
                                                  document_target: 'doc',
                                                  action: 'click->document#info'
                                                  },
                                                  style: 'text-decoration: none; color: black' do  %>
                    <i class="fa-regular fa-file-lines"></i>
                  <% end %>
                <% end %>
                  <%= link_to new_supplier_document_path(supplier), class: 'me-4', data: {
                                                document_target: 'new',
                                                action: 'click->document#new'
                                                }, style: 'text-decoration: none; color: black' do   %>
                    <i class="fa-solid fa-folder-plus"></i>
                  <% end %>
            </div>
          </div>
          <div data-info-target='insert' data-document-target='insert' style='background:white'></div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <h1>Vous n'avez pas de fournisseurs</h1>
<% end %>

app/views/suppliers/_error.html.erb
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= "Une erreur c'est produite, le fournissuer n'a pas été enregistré" %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>

app/views/suppliers/_form.html.erb
<div class="p-3 d-flex justify-content-between">
  <%= simple_form_for(supplier,
                data: {
                  info_target: "form",
                  action: "submit->info#send"
                  }) do |f| %>
      <%= f.input :name, label: false, input_html: {placeholder: 'nom du fournisseur', data: { create_target: 'input'}}  %>
      <%= f.input :contact, label: false, input_html: {placeholder: 'nom du contact', data: { create_target: 'input'}}  %>
      <%= f.input :bio, as: :boolean, checked_value: true %>
      <%= f.button :submit, 'Mettre à jour', class: 'btn btn-outline-primary', data: {
                                                                disable_with: false,
                                                                bs_dismiss: 'modal'
                                                              } %>
  <% end %>
  <div data-action="click->info#close">
    <i class="fa-solid fa-xmark"></i>
  </div>
</div>

app/views/suppliers/_index.html.erb
<div class="m-4"data-controller="create" data-create-target="index" >
  <div class="container">
    <div class="row">

<!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#supplierModal" style="width:350px;">
        <i class="fa-sharp fa-solid fa-plus"></i> Ajouter un nouveau fournisseur
      </button>

<!-- Modal -->
      <div class="modal fade" id="supplierModal" tabindex="-1" aria-labelledby="supplierModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Nouveau fournisseur</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="col-8 m-3">
              <%= simple_form_for(supplier,
                          data: {
                            create_target: "form",
                            action: "submit->create#send"
                            }) do |f| %>
                <%= f.input :name, label: false, input_html: {placeholder: 'nom du fournisseur', data: { create_target: 'input'}}  %>
                <%= f.input :contact, label: false, input_html: {placeholder: 'nom du contact', data: { create_target: 'input'}}  %>
                <%= f.input :bio, as: :boolean, checked_value: true, unchecked_value: false %>
                <%= f.button :submit, class: 'btn btn-outline-primary', data: {
                                                                          disable_with: false,
                                                                          bs_dismiss: 'modal'
                                                                        } %>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div data-create-target='insert'></div>
    <div data-content-target="insertCard"></div>
</div>

app/views/suppliers/_info_supplier.html.erb
<h2><%= supplier.name %></h2>

app/views/suppliers/_new_supplier.html.erb
<div class="alert alert-primary alert-dismissible fade show m-1" role="alert">
  <%= "Fournisseur bien enregistré" %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>

<div data-controller="info" style='background:white'>
  <div class="card-product mt-5">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
    <div class="card-product-infos">
      <h2><%= supplier.name %></h2>
    </div>
  </div>
</div>

app/views/suppliers/_update_supplier.html.erb
<div class="alert alert-primary alert-dismissible fade show m-1" role="alert">
  <%= "Produit bien enregistré" %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>